export const licenses = [
  "None Yet, I'm New!",
  "USCG Master 100GT",
  "USCG Master 200GT",
  "USCG Master 500GT",
  "USCG Master 1600GT",
  "USCG Master 3600GT",
  "USCG Master Unlimited",
  "STCW Basic Safety Training",
  "RYA Yachtmaster",
  "RYA Day Skipper",
  "RYA Coastal Skipper",
  "ICC (International Certificate of Competence)",
  "MCA Master 200GT",
  "MCA Master 500GT",
  "MCA Master 3000GT",
  "MCA Master Unlimited",
  "MCA OOW (Officer of the Watch)",
  "MCA Chief Mate 3000GT",
  "MCA Chief Mate Unlimited",
  "RYA Powerboat Level 2",
  "STCW Basic Training",
  "STCW Advanced Firefighting",
  "STCW Proficiency in Survival Craft and Rescue Boats",
  "STCW Engine Room Rating",
  "STCW Able Seafarer Engine",
  "STCW Officer of the Watch (Engine)",
  "MCA Marine Engine Operator License (MEOL)",
  "MCA AEC 1",
  "MCA AEC 2",
  "MCA Chief Engineer Y4",
  "MCA Chief Engineer Y3",
  "MCA Chief Engineer Y2",
  "MCA Chief Engineer Y1",
  "MCA Small Vessels Second Engineer Unlimited 3000GT",
  "MCA Small Vessels Chief Engineer Unlimited 500GT",
  "MCA Small Vessels Second Engineer Unlimited 3000GT",
  "MCA Engineer Officer of the Watch Unlimited",
  "MCA Chief Engineer Unlimited",
  "MCA Second Engineer Unlimited",
  "MCA Electro-Technical Officer (ETO)",
  "USCG Designated Duty Engineer (DDE)",
  "USCG Assistant Engineer",
  "USCG Chief Engineer",
];
